# Generated by Django 6.0.7 on 2026-07-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aadhi_app', '0003_registration_checked_in_registration_payment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=150)),
                ('business_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True)),
                ('company_address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('industry_type', models.CharField(blank=True, choices=[('corporate', 'Corporate'), ('startup', 'Startup'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('fitness', 'Fitness'), ('it', 'IT'), ('retail', 'Retail'), ('real_estate', 'Real Estate'), ('banking', 'Banking'), ('ngo', 'NGO'), ('government', 'Government'), ('other', 'Other')], max_length=20)),
                ('sponsorship_category', models.CharField(blank=True, choices=[('title', 'Title Sponsor'), ('gold', 'Gold Sponsor'), ('silver', 'Silver Sponsor'), ('bronze', 'Bronze Sponsor'), ('custom', 'Custom Sponsorship')], max_length=20)),
                ('budget_range', models.CharField(blank=True, choices=[('50k_1l', '₹50,000 - ₹1,00,000'), ('1l_5l', '₹1,00,000 - ₹5,00,000'), ('5l_10l', '₹5,00,000 - ₹10,00,000'), ('10l_plus', '₹10,00,000+'), ('custom', 'Custom Budget')], max_length=20)),
                ('events_interested', models.CharField(blank=True, max_length=500)),
                ('company_description', models.TextField(blank=True)),
                ('marketing_objectives', models.TextField(blank=True)),
                ('additional_requirements', models.TextField(blank=True)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='sponsors/logos/')),
                ('company_brochure', models.FileField(blank=True, null=True, upload_to='sponsors/brochures/')),
                ('sponsorship_proposal', models.FileField(blank=True, null=True, upload_to='sponsors/proposals/')),
                ('agreed_to_terms', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sponsor Inquiry',
                'verbose_name_plural': 'Sponsor Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
